spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework: info
    org.spring.springboot.dao: debug

server:
  port: 18080

mybatis:
  type-aliases-package: com.zzq.pro.model

---
spring:
  profiles: prod
server:
  port: 18081
